name: dw-clickhouse

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8.9.95-alpine
    env_file:
      - ./clickhouse.env
    extra_hosts:
      - host.docker.internal:host-gateway # Used for connection to Postgres created by PeerDB
    ports:
      - ${DW_CLICKHOUSE_HTTP_PORT}:8123
      - ${DW_CLICKHOUSE_TCP_PORT}:9000
    volumes:
      - ../../clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ../../clickhouse/config.d/override.xml:/etc/clickhouse-server/config.d/override.xml:ro
      - ../../clickhouse/users.d/override.xml:/etc/clickhouse-server/users.d/override.xml:ro
      - clickhouse-data:/var/lib/clickhouse:rw
    healthcheck:
      test: wget --no-verbose --spider http://0.0.0.0:8123/ping || exit 1
      interval: 1s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
    cap_add:
      - CAP_SYS_NICE # https://github.com/ClickHouse/ClickHouse/issues/68747#issuecomment-2306631664

volumes:
  clickhouse-data:

networks:
  default:
    name: dw
